name: Setup Vouch
description: "Install Nushell and make the vouch CLI available on PATH."

runs:
  using: composite
  steps:
    - id: check-nu
      shell: bash
      run: |
        if command -v nu &>/dev/null; then
          echo "found=true" >> "$GITHUB_OUTPUT"
        fi

    - if: steps.check-nu.outputs.found != 'true'
      uses: hustcer/setup-nu@920172d92eb04671776f3ba69d605d3b09351c30 # v3.22
      with:
        version: "*"

    # Expose the checked-in wrapper on PATH and persist the module
    # location for subsequent workflow steps that call `vouch`.
    - shell: nu {0}
      run: |
        let vouch_lib_dir = (
          "${{ github.action_path }}"
          | path join ".." ".." "vouch"
          | path expand
        )

        $"VOUCH_LIB_DIR=($vouch_lib_dir)" | save --append $env.GITHUB_ENV
        "${{ github.action_path }}" | save --append $env.GITHUB_PATH
