name: Test

on:
  push: {}
  pull_request:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pinact:
    name: "GitHub Actions Pins"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: DeterminateSystems/nix-installer-action@main
      - name: pinact check
        run: nix develop -c pinact run --check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prettier:
    # Run on any push in this repo.
    # Run on PRs to main ONLY if the PR head is a fork (so we don't double-run for same-repo PRs).
    if: >
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.head.repo.full_name != github.repository)

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: DeterminateSystems/nix-installer-action@main
      - name: prettier check
        run: nix develop -c prettier --check .

  test:
    if: >
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.head.repo.full_name != github.repository)

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: hustcer/setup-nu@92c296ba1ba2ba04cc948ab64ddefe192dc13f0c # v3.23
        with:
          version: "*"
      - name: Fast tests
        run: nu tests/run.nu --fast
      - name: Slow tests
        run: nu tests/run.nu --slow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  setup-vouch:
    if: >
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.head.repo.full_name != github.repository)

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./action/setup-vouch
      - run: vouch
      - run: vouch add --help
